  // -    -   -   -   -  //
 // JAVASCRIPT CARNIVAL //
// -    -   -   -   -  //

//Collect all td HTML elements and convert to an array
let tableCellsArray = Array.from(document.getElementsByTagName('td'))

//Calls and holds random index number generated by function
let randomIndex = generateRandomIndex()

//Variable for holding the array with it's randomly generated cell index position
let randomCell = tableCellsArray[randomIndex]

let mole
let totalWhacks = 0

//Sets up the whacking sound effect in the game
let audio = new Audio()
audio.src = "whack-audio.wav"

generateMole()

//Creates mole
function generateMole() {

  mole = document.createElement('img')
  mole.setAttribute('id', 'mole')
  mole.src = 'mole.PNG'
  tableCellsArray[generateRandomIndex()].appendChild(mole)
  mole.onclick = whackMole

}

//Removes the mole once clicked and plays whacking audio
function whackMole() {

  countDown()
  mole.remove()
  audio.play()
  totalWhacks++
  whackCounter()
  generateMole()
  countDown()
  console.log(mole)
  
}

//Updates the score displayed on the HTML page
function whackCounter() {

  let whackCounter = document.getElementById('score')
  whackCounter.innerHTML = totalWhacks

}

//Sets and updates the countdown timer for the game
function countDown(){ 

  let count = 10

  if (totalWhacks === 0)
    setInterval(function() {
      count--

      if(count >= 0) {
        time = document.getElementById('countdown')
        time.innerHTML = count

      if(count === 0)
      alert('Your score is ' + totalWhacks)

      }
    }, 1000);
  
}

//Generates a random index number
function generateRandomIndex() {

  return Math.floor(Math.random() * 25)

}

console.log(countDown)

console.log("Whack-a-Mole!")